<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <main role="main" class="mb-3">
        <div class="jumbotron bg-info">
            <div class="container">
                <h1>HeyHome</h1>

                <div class="input-group">
                    <span class="input-group-text bg-white border-0">@</span>
                    <input type="text" name="" id="floatingInputGroup2" class="form-control border-0" placeholder="Try 3 bedroom flats near me">
                    <span class="input-group-text bg-white border-0">@</span>
                </div>
            </div>
        </div>
    </main>
    <div class="container">
        <div class="d-flex">
            <div >
                <a href="" class="btn btn-white d-flex align-items-center">
                    <span class="mr-3"><!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 32 32">
                            <title>office</title>
                            <path
                                d="M0 32h16v-32h-16v32zM10 4h4v4h-4v-4zM10 12h4v4h-4v-4zM10 20h4v4h-4v-4zM2 4h4v4h-4v-4zM2 12h4v4h-4v-4zM2 20h4v4h-4v-4zM18 10h14v2h-14zM18 32h4v-8h6v8h4v-18h-14z">
                            </path>
                        </svg>
                    </span>
                    Apartement
                </a>
            </div>
            <div class="ml-3">
                <a href="" class="btn btn-white d-flex align-items-center">
                    <span class="mr-3"><!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="24" height="24" viewBox="0 0 32 32">
                            <title>home2</title>
                            <path
                                d="M16 1l-16 16 3 3 3-3v13h8v-6h4v6h8v-13l3 3 3-3-16-16zM16 14c-1.105 0-2-0.895-2-2s0.895-2 2-2c1.105 0 2 0.895 2 2s-0.895 2-2 2z">
                            </path>
                        </svg>
                    </span>
                    Condos
                </a>
            </div>
            <div class="ml-3">
                <a href="" class="btn btn-white d-flex align-items-center">
                    <span class="mr-3">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="24" height="24" viewBox="0 0 34 32">
                            <title>library</title>
                            <path
                                d="M32 30v-2h-2v-12h2v-2h-6v2h2v12h-6v-12h2v-2h-6v2h2v12h-6v-12h2v-2h-6v2h2v12h-6v-12h2v-2h-6v2h2v12h-2v2h-2v2h34v-2h-2z">
                            </path>
                            <path d="M16 0h2l16 10v2h-34v-2l16-10z"></path>
                        </svg>
                    </span>
                    Studios
                </a>
            </div>
        </div>

        <div class="pt-5">
            <h5 class="text-muted">Featured Listings</h5>
            <div class="row">
                <div class="col-md-4">
                    <div class="card border-0">
                        <img src="{{asset('img/bg.jpg')}}" alt="">
                        <div class="card-body">
                            <h4 class="text-info">Apartment</h2>
                                <div class="d-flex justify-content-between">
                                    $340/mo
                                </div>
                                <div>
                                    <span>

                                    </span>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0">
                        <img src="{{asset('img/bg.jpg')}}" alt="">
                        <div class="card-body">
                            <h4 class="text-info">Apartment</h2>
                                <div class="d-flex justify-content-between">
                                    $340/mo
                                </div>
                                <div>
                                    <span>

                                    </span>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-0">
                        <img src="{{asset('img/bg.jpg')}}" alt="">
                        <div class="card-body">
                            <h4 class="text-info">Apartment</h2>
                                <div class="d-flex justify-content-between">
                                    $340/mo
                                </div>
                                <div>
                                    <span>

                                    </span>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>